### ISSUE TITLE
[discussion][enhancement] middleware for introspection call

### ISSUE THREAD

**Issue by jasondeutsch** [nautilus/graphql#12]
I have a case which requires setting certain headers for the initial `IntrospectRemoteSchemas` call. 
Presently, I do not see a built in way to provide this and I am seeking feedback on:
1. if my evaluation is correct  
2. adding this capability.

If an addition is required perhaps one approach could including new-ing up an introspection request object of some sort and then calling `WithMiddlewares(...)`

**Comment by AlecAivazis** [comment]
Hey @jasondeutsch. You are correct that we'll need to wire a few things up so that Request middlewares get included in the introspection. How important is it that this middleware is only included with as part of the introspection?

**Comment by jasondeutsch** [comment]
Middleware, in my use case, will be needed for all requests.

**Comment by jasondeutsch** [comment]
I'm closing this since I realized the use cases can be full-filled without code changes.
