### ISSUE TITLE
Union / fragments handling error in 0.0.17

### ISSUE THREAD

**Issue by obukhov** [nautilus/graphql#21]
Hello! We tried to update to version 0.0.17 version of this package and started getting following errors on  handling our queries (I assume actually parsing the query itself). All errors are referring union types:
```
Fragment cannot be spread here as objects of type \"<some union type>\" can never be of type \"< part of that union >\".
```

Basically, any union spread in the query causes this error.

We solved by rolling back to 0.0.16 thanks if you will have time to look into it!

**Comment by AlecAivazis** [comment]
@JohnStarich mind taking a look at this? It must be related to your recent PR

**Comment by JohnStarich** [comment]
Sure thing, I'll take a look. Feel free to assign me

**Comment by JohnStarich** [comment]
Hey @obukhov, do you have a minimal example that exhibits the issue?

**Comment by obukhov** [comment]
Sorry, haven't had time yet to dig into this issue. The issue appeared together with gateway usage. I'll try to debug / trace the issue in more details this week

**Comment by JohnStarich** [comment]
Hey @obukhov, any luck so far? If you have an example using the gateway, that'd be helpful too.

I'd be happy to fix an issue if present, just don't know what to look for yet 🙂

**Comment by JohnStarich** [comment]
@obukhov or @AlecAivazis Any luck? I've been unable to reproduce the above issue.

**Comment by JohnStarich** [comment]
@obukhov I'll go ahead and close for now since we haven't heard back in a while. Feel free to re-open when you find out more!

**Comment by JohnStarich** [comment]
@obukhov I think I missed this in my first attempts because the tests skipped the introspection step, which contained the bug.

@sGy1980de found the problem and fixed it! 🎉
