### ISSUE TITLE
[Question] : Do we have retry option for IntrospectAPI().

### ISSUE THREAD

**Issue by chetanugale** [nautilus/graphql#22]
Scenario:
We have multiple remote APIs which serve our graphql server for response.
We're facing intermittent issue for APIs while using IntrospectAPI() where our APIs are in working/serving state but IntrospectAPI() return 404 API not found/ Network error.Do we have any param which can be used to retry establishing connection with IntrospectAPI().
Any other solution to handle the issue is also appreciated

**Comment by JohnStarich** [comment]
Hey @chetanugale, definitely agree that's a useful feature. You can try out the new [`IntrospectWithRetrier()`](https://pkg.go.dev/github.com/nautilus/graphql@v0.0.22#IntrospectWithRetrier) option now in `v0.0.22`! 🚀 

It's pretty extensible and includes a decent retrier implementation in [`CountRetrier`](https://pkg.go.dev/github.com/nautilus/graphql@v0.0.22#CountRetrier).
