### ISSUE TITLE
..\github.com\carted\graphql\language\printer\printer.go:372:9: undefined: ast.NullValue

### ISSUE THREAD

**Issue by SupratickDey** [nautilus/graphql#9]
# github.com/carted/graphql/language/printer
..\github.com\carted\graphql\language\printer\printer.go:372:9: undefined: ast.NullValue

**Comment by RayDevel** [comment]
Same issue here (winx64 platform)

**Comment by AlecAivazis** [comment]
@SupratickDey  - thanks for reporting. Mind giving me a bit more info?

When did you receive this?
